fix: Align snuba-metric value field with ingest-metrics
We are getting type-checking errors in https://github.com/getsentry/sentry/pull/46782, because

```
src/sentry/sentry_metrics/consumers/indexer/batch.py:383: error: Incompatible types (expression has type "Union[float, List[int], List[Union[int, float]]]", TypedDict item "value" has type "Union[int, float, List[int]]")  [typeddict-item]
```

This is because `List[int]` can't be cast to `Lint[Union[float, int]]`.

We should just reuse the definition sometime, but for now let's
copypaste.